sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 117418
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBKjKpTAMoGizuKyQ4c
    access-key-secret: 5uoQBuLGtG2Kgs72DNNByhfh8nGGS7
    bucket-name: chaochaodbucket
  redis:
    host: localhost
    port: 6379
    #    password: 117418
    database: 0